//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortEF6toCore.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int IssueId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedByName { get; set; }
    
        public virtual User CreatedBy { get; set; }
        public virtual Issue Issue { get; set; }
    }
}
